version: '3.8'
services:
  #Redis 快取服務
  redis:
    image: redis:7-alpine
    container_name: allpass_redis_container
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_HOST_PORT:-6379}:${REDIS_PORT:-6379}"
    networks:
      - allpass-network
    restart: unless-stopped

  #Postgres(postgis) 服務
  postgis:
    image: postgis/postgis:16-3.4
    container_name: allpass_postgis_container
    env_file:
      - ./.env
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - allpass-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-allpass_user} -d ${POSTGRES_DB:-allpass_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgis_data:
    name: allpass_postgis_data
  redis_data:
    name: allpass_redis_data

networks:
  allpass-network:
    driver: bridge